### ISSUE TITLE
Add Twitter/Github/Facebook login?

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#104]
With AllAuth should be simple to add Twitter or Github or Facebook (or almost any social media provider) for login. Should we do it? If so, which ones?

**Comment by casassg** [comment]
@hackupc/dev Thoughts here

**Comment by wailingtam** [comment]
I’ve used it before to add Fb and LinkedIn logins. It should be quite easy. I haven't seen many hackathons (none?)  use a different login from email. If we do so, Github would be my first choice

**Comment by dasilvacontin** [comment]
Which login are you talking about?

If it's for hackers, making GitHub the main option can be a nice nudge into making them create a GitHub account, from which they'll benefit via increased collaboration.

**Comment by casassg** [comment]
Yeah it's for hacker to register. We are enabling sign up for the new version of the backend.

**Comment by ofpau** [comment]
+1 to GitHub.

**Comment by casassg** [comment]
Alright, let's do it: #108

**Comment by casassg** [comment]
Closing this
