### ISSUE TITLE
Improve food allergies and special need input

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#112]
Options:

- Add an `Other` choice in diet and a free field if selected
- Add a `special needs` field
- Add email and message urging to contact us if hacker has special need we need to know

**Comment by yoelcabo** [comment]
I would say, food allergies or any other special needs.
Ideas:
1. Free answer box to input any special need.
2. Add a line saying: "If you have any special need you want us to know about, you can send us an email to blahblah@hackupc.com

**Comment by casassg** [comment]
Added "If you have any special need you want us to know about, you can send us an email to contact@hackupc.com". I want to get back at this, so I'm leaving it open

**Comment by casassg** [comment]
Fixed in #131
