### ISSUE TITLE
Hosting question

### ISSUE THREAD

**Issue by AlbertSuarez** [HackAssistant/registration#119]
Add a question in hacker form asking for the interest to host a international hacker. Add a great disclaimer saying we guarantee nothing on the attendee side of things.

**Comment by casassg** [comment]
Ups, just saw this. Should we add it now? What was the ultimate decision?

**Comment by AlbertSuarez** [comment]
I wouldn't add it. It's too late I think

**Comment by dasilvacontin** [comment]
Whoops.

**Comment by dasilvacontin** [comment]
We can send an email later to those who've been accepted.

**Comment by casassg** [comment]
Agree
