### ISSUE TITLE
Discussion: Colors and design

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#121]
Add here colors...

**Comment by casassg** [comment]
@oriol20 proposed an alternative with his baggage project. Add the image as background. https://s2.postimg.org/sffmbjcux/Captura_de_2017-08-08_19_39_11.png Thoughts?

**Comment by casassg** [comment]
Would really appreciate comments from @hackupc/design here

**Comment by elena20ruiz** [comment]
Love it <3

Could it be a lot to change the font text button ??? To have consistence.

And I can propose some tips to improve (that is from my personal opinion), but not worries if you do not like it.

1. I think that in this case it is more important 'Baggage check-in' than 'hackupc'. I would put:
> BAGGAGE CHECK-IN (bigger than HackUPC)
> HACKUPC
(I added an exemple)

In fact, I do not know if HackUPC is strictly necessary, logo better ?. Who will see this page?

2. The second thing I would chage to improve it (but now for me it's ok) are the text boxes. I would prefer with background in beige or gray and quit the border line.

Although, I like it! 
![example](https://user-images.githubusercontent.com/15120635/29088978-2888fece-7c7b-11e7-9cca-2d6a895b181b.png)

**Comment by oriolclosa** [comment]
In fact this page is only intended to be displayed to the volunteers/organizers in the infodesk. Love the logo!

For the textboxes, I'll try your proposed changes, but deleting the border won't look good, I've already tried this.

For the font in the buttons, which one should it be?

**Comment by elena20ruiz** [comment]
Yes, you're right. Light color text boxes without border it's difficult :/ (I said that too fast)

And the font is: Gotham Regular. (I think it is already installed on backend)

**Comment by oriolclosa** [comment]
I'll change that now, do you have the logo you just shared with transparent background?

**Comment by elena20ruiz** [comment]
@oriol20 

1. PNG and PSD (DEV folder) Titles: https://drive.google.com/drive/u/1/folders/0B9WjsYaZc60leHJPY0dmbEEyNnM
2. LOGO images: https://drive.google.com/drive/u/1/folders/0B9WjsYaZc60lSlF3S1QwVGV2UkE

**Comment by oriol20** [comment]
![baggage v2](https://user-images.githubusercontent.com/10714286/29091689-0c5b225a-7c84-11e7-964b-587e8af3e38a.png)

**Comment by oriolclosa** [comment]
Centered logo
![baggage v2](https://user-images.githubusercontent.com/10714286/29091751-3a00e398-7c84-11e7-91dd-e7bd53094260.png)

Side logo v1
![baggage v3](https://user-images.githubusercontent.com/10714286/29091724-27e079bc-7c84-11e7-8b15-0e10e71b278b.png)

Side logo v2
![baggage v4](https://user-images.githubusercontent.com/10714286/29092279-24205df4-7c86-11e7-9205-0f2711d09c97.png)

I personally prefer the sided v2, but also the centered because the sided v1 seems really squared.

**Comment by casassg** [comment]
Please can we keep this conversation about the current repo and move the baggage checkin conversation to the baggage checkin repo issues? :sweat_smile: 

https://github.com/hackupc/baggage/issues/5

**Comment by casassg** [comment]
Also, regarding font. Gotham Regular is on frontend, it's not used on backend, mainly because I didn't have enough time to decide where to use and where to keep using Ek mukta

**Comment by elena20ruiz** [comment]
Yep I know that in backend it is not Gotham putted but thinking that button style is the same, why can not be in Gotham? The other font styles doesn't matter.

**Comment by elena20ruiz** [comment]
Ok, nothing. I understood that check-in was in backend repo.

**Comment by casassg** [comment]
Closing this. Fonts have changed and this is going to be hackathon agnostic
