### ISSUE TITLE
Open resume PDF files in the browser

### ISSUE THREAD

**Issue by ofpau** [HackAssistant/registration#127]
In the review applications view, make the PDFs open with the browser viewer instead of starting to download. [This seems ](https://stackoverflow.com/a/11894771) to be a way to do it. 
Requested by @rgascons on Slack.

**Comment by casassg** [comment]
Problem: the CV links are from Typeform, we just "show" them. We can't change HTTP header from it.

**Comment by casassg** [comment]
Closing this. There's not much we can do about it
