### ISSUE TITLE
Manage email list from sendgrid

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#13]
Whenever a user confirms -> Add him to the email list
Whenever a user cancels -> Remove him from the email list

**Comment by casassg** [comment]
@ofpau do you think you can add this to your current tasks?

**Comment by ofpau** [comment]
Yes, I'll take this then

**Comment by ofpau** [comment]
I think the **steps needed** will be something like:

1. Create sendgrid campaign and list (can be done manually from the website)
2. When a user confirms, add them as a recipient (contactdb API).
3. Right after that, [add them to the mailing list](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#add-a-single-recipient-to-a-list). Note that we need the recipient ID, so the previous step is required.
4. If the user cancels attendance, remove them from the mailing list (if they had been added before).

**Questions**:
 1. Do we keep the users that canceled their attendance as recipients or we delete their contact as well? Even if we kept their recipient, after being removed from the list they wouldn't receive further emails, but we'd keep their contact, so I'm not sure removing the recipient has any benefits. 
2. I suggest using the **[SendGrid Python Library](https://github.com/sendgrid/sendgrid-python)** to simplify the interaction with the SendGrid API. Is that alright?
3. Does this process need to start when a user _confirms_ or when a user _applies_ to the hackathon? It might make sense to add people as recipients as soon as they apply. This might be a bit of unnecessary work right now though, so just leaving it here as a thought.

**Comment by casassg** [comment]
**Answers:**
1. Always keep recipients. We can manually clean them if needed (I don't expect it to be needed at any point soon)
2. Yes, as long as the library has official support from SendGrid and is actively supported.
3. We can add them when they apply, we will need to be careful to remove them if the list increases so much. Create a function to retrieve recipient id, or add it to the system if it doesn't exist.

**Comment by ofpau** [comment]
Working on this [here](https://github.com/hackupc/mercuryhack/commits/mail_list). Created a _MailListManager_ that will do the work needed, and added a field in the application model to keep track of the sendgrid _recipient_id_ of each user. Left to do: call the correspondent methods when someone confirms/cancels attendance.

**Comment by casassg** [comment]
closed at #28
