### ISSUE TITLE
Add blacklist system

### ISSUE THREAD

**Issue by rgascons** [HackAssistant/registration#146]
We need to standardize this process and avoid future situations where a Hacker that is in our internal blacklist has been accidentally accepted.

My proposal:

1. Add a blacklist structure in the system that can be edited by admins only
    - This blacklist must have fields like: Name | Motive of bann | Date of bann
2. This list can be seen by all HackUPC staff
3. When a blacklisted user registers, the following happens:
    3.1. Show an alert in the application of the blacklisted user so we can reject him/her later
    3.2. Disable the application from being voted while its rejected status is resolved
    3.3. Finally reject the application (notifying the affected user) or uplift the bann

In point 3, sub-points 3.1 and 3.2 will require new code in the system, while 3.3 is better to be manually handled by the directors or the appointed staff.

**Comment by casassg** [comment]
Given the fact that we no longer plan on keeping this between editions, should we close this?

**Comment by casassg** [comment]
@Casassarnau has this been done at hackUPC?

**Comment by Casassarnau** [comment]
No, we are doing it now at Hackassistant. We are doing it a bit diferent but the idea is the same, I'm taking this issue. The one in charge of it right now is @Ferja.
