### ISSUE TITLE
Ask if hacker is from FIB-UPC, and if so, what degree/master he/she is enrolled to

### ISSUE THREAD

**Issue by AlbertSuarez** [HackAssistant/registration#152]
It's a Maria Teresa (vice-dean) request:

> podríeu afegir al formulari d'inscripció que el participant indiqui si és fiber o no i, en cas afirmatiu, quina titulació està cursant (GEI, MAI, MIRI, MEI, GCED, MasterSecundaria).

**Comment by qaisjp** [comment]
fiber?

**Comment by casassg** [comment]
@qaisjp It's how we call people studying at FIB (Informatics Faculty of Barcelona) XD

**Comment by casassg** [comment]
Will take a look at how to do that. I need to do a refactor on the way of creating the forms

**Comment by qaisjp** [comment]
ah cool :D We say Infer (School of Informatics)

**Comment by casassg** [comment]
Once we have this as a standalone repo and use a fork for HackUPC, we may be able to do it

**Comment by qaisjp** [comment]
Would it be to complex to move this into a feature titled "Targeted Questions", allowing you to ask questions ("What degree?") based on a predicate (`school=FIB-UPC`)?

**Comment by casassg** [comment]
Currently, there's no easy way to do this. There are a few targeted questions though (Projects you have done only appear if this is not your first hackathon. The only problem is that it's quite manual. I may look to see if there's an easier way to do it.

**Comment by AlbertSuarez** [comment]
Closed since we are not gonna implement this.
