### ISSUE TITLE
Add auto migrate for heroku automated releases

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#164]
My apologies @qaisjp I got the bug reports after the release happened. Should be alright now!

This has been fixed on https://github.com/HackAssistant/registration/commit/4be2f36a905bec3b583a8f03cb75ebb54c137190

**Comment by qaisjp** [comment]
No worries! quick question: this project is looking **extremely** promising.

When will HackCU 2018 happen / applications go out? We're hoping to run a hackathon around March, and I'm wondering whether we should use HackAssistant _this year_, or _next year_.

**Comment by casassg** [comment]
HackCU is happening on late Feb 2018. Why though? If you fork it you should be able to deploy your own version of HackAssistant. For HackCU actually we have an entire separate repo and deployment on AWS (still on beta though, applications will go out soon - betamy.hackcu.org)

The registration.gerard.space is just a heroku deployment I made to test that heroku deploy button works (and then kept it bc its free). So we are not using it.

I'm not sure if I understood your question.
