### ISSUE TITLE
User losing input data after changing tab on the application page 

### ISSUE THREAD

**Issue by qaisjp** [HackAssistant/registration#189]
> I filled out everything on "Home" and then thought I can fill out "Team", and I lost all my written data
>
> I thought it was a single page application

(user report)

I'll send a PR if i get the chance to work on it, ~~doesn't seem too important~~ multiple seem to be running into this issue so I'll have to do this soon.

a potential solution would be to show an `alert()` `onclose` if input was made

**Comment by qaisjp** [comment]
Is this sufficient enough? https://github.com/compsoc-edinburgh/hackassistant-registration/commit/a11a2ead2bc17a5ebf54613f45bf092b8e9fbcf7

I feel like the setTimeout is a bit hacky but it seems like the only option since there's no easy way to programmatically check if all the fields in a form validates (clientside)

(setting it back is necessary to prevent attempted submissions of incomplete forms from removing the check)

if the commit there is good enough, i can send a pr over

**Comment by qaisjp** [comment]
Not good enough. 

https://stackoverflow.com/questions/6903457/is-the-onbeforeunload-event-not-supported-on-iphone

We should catch an `a href` click ourselves, watching out to make sure they aren't ctrl+clicking anywhere

**Comment by casassg** [comment]
Quick fix for this: Show team tab only when they finished application. What do you think @qaisjp ?

I think it will avoid having hackish stuff on js and will also avoid confusion. If this works I can submit a PR myself tomorrow, should be simple.

**Comment by qaisjp** [comment]
That solution sounds good to me.
