### ISSUE TITLE
Fix bug on CV upload

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#192]
## Is this a BUG REPORT or FEATURE REQUEST?

CV is not uploaded due to Mixin pushed at #183 

## What happened

- CVs are not uploaded when filling application

## What you expected to happen

- CVs to be stored after submitting them

## How to reproduce it (as minimally and precisely as possible)

1. Fill application with resume
2. Submit application
3. Check application on Application tab
4. No CV is uploaded if running on Heroku or Docker

**Comment by qaisjp** [comment]
Docker does have support for file system uploads, cc @hreeder

**Comment by casassg** [comment]
Then you should add it to your deployment @qaisjp . At the moment it's not storing my CV. It's a minor issue, but receipts are way more important and will happen the same.

I also have a PR ready to add the ability to do it with Dropbox.

**Comment by qaisjp** [comment]
Wait @casassg are you saying that my.hacktheburgh.com isn't uploading CVs, or something else?

**Comment by casassg** [comment]
Yes, that's what I'm saying. I registered today to check if everything was fine.

**Comment by qaisjp** [comment]
Crap. I've had a quick look and it seems that uploads through the admin
panel work fine but not through the dashboard. I may have broken something
whilst working on my modifications

**Comment by casassg** [comment]
Let me know if you find something 👍

**Comment by qaisjp** [comment]
Yeah, hmm, can't seem to find where the issue is at first look. :|

**Comment by qaisjp** [comment]
@casassg #183 causes this.

(tested by changing `class ApplicationForm(OverwriteOnlyModelFormMixin, BetterModelForm):` to `class ApplicationForm(BetterModelForm):`)

**Comment by qaisjp** [comment]
Temporary fix issued here https://github.com/compsoc-edinburgh/hackassistant-registration/commit/be3a72d7743182197e10c6831cbb8368cca01ec7

**Comment by casassg** [comment]
Bug fixed. PRing now.

**Comment by casassg** [comment]
It should be all good now. Tested on localhost with several scenarios.

**Comment by qaisjp** [comment]
Thank you!
