### ISSUE TITLE
String translation to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [HackAssistant/registration#194]
Hi, I'm interested in collaborating on your project as a translator into Spanish which is my native language

**Comment by casassg** [comment]
Hi @LuigiBaute I have not enabled translation for the project just yet. Django Translations needs to be configured and the strings to be translated need to be marked (see: https://docs.djangoproject.com/en/2.0/topics/i18n/translation/). I can be quite some work. If you want, you could fork the repo and start marking strings. I can provide with any assistance as I have done it for other projects before. 


----

Hola @LuigiBaute no he habilitado traducciones para este proyecto aun. Se tiene que habilitar Django Translations y marcar los textos a traducir (referencia: https://docs.djangoproject.com/en/2.0/topics/i18n/translation/ ). Puede ser una tarea larga, hay bastante texto por traducir. Si quieres puedes hacer un fork del repositorio y empezar a hacer cambios allí. Puedo ayudarte si es necesario ya que lo he hecho antes para otros proyectos. Ademas, el castellano tambien es mi lengua nativa, soy de Barcelona.

----

Are you able to collaborate on English fluently though? This project has contributors from non-Spanish speaking countries so I would like to keep conversations in English if possible.

**Comment by LuigiBaute** [comment]
Yes I can collaborate on English as well, but I mostly do translations.
