### ISSUE TITLE
Files should not be publicly accessible

### ISSUE THREAD

**Issue by qaisjp** [HackAssistant/registration#206]
Currently you can visit any file without being authenticated. We should add authentication for receipts (organiser only) and CVs (organisers and uploaders).

Happy to work on this - I'll self assign once work has started.

**Comment by casassg** [comment]
Mmmm this may be tricky. Files are made available through nginx/Apache as static assets. I don't believe this should be a problem. Unless you know someone else's resume name

**Comment by casassg** [comment]
There's a PR on this at the HackUPC repo. Will add this here once HackUPC is done 

https://github.com/hackupc/registration/pull/22
https://github.com/hackupc/registration/pull/21

**Comment by casassg** [comment]
@oriolclosa Any chance to cherrypick the PRs here?

**Comment by casassg** [comment]
@Casassarnau can you pull the changes from HackUPC?

**Comment by Casassarnau** [comment]
Done
