### ISSUE TITLE
Reimbursement submission for friends 500s

### ISSUE THREAD

**Issue by qaisjp** [HackAssistant/registration#208]
Error received:

```
AttributeError at /reimbursement/dashboard/
'Exception' object has no attribute 'message'
```
![image](https://user-images.githubusercontent.com/923242/36956156-ad2ce6d4-2024-11e8-8cda-9f68581bd80a.png)

Should have a friendly client side error message.

![image](https://user-images.githubusercontent.com/923242/36956171-c6b5866a-2024-11e8-906b-fdca069ebd6f.png)

**Comment by qaisjp** [comment]
appears to be a difference between py2 and py3.

https://stackoverflow.com/questions/7075200/converting-exception-to-a-string-in-python-3#comment8466946_7075318

**Comment by casassg** [comment]
Yeah, I think doing `str(e)` should solve it? Not sure though

**Comment by Casassarnau** [comment]
This is working now, closing tis issue
