### ISSUE TITLE
Add attendance views

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#21]
We want our volunteers to check people in. In that way, we need to create new views so that we can check-in people without having to be admins.

- [x] QR scanner view -> when QR detects a valid token redirect to check-in page
- [x] Manual confirmed list view 
  - [x] Search by token or name or last name or email
  - [x] Show results of search and link to check-in view
- [x] Check-in view-> should have information about the hacker (minimal) so that volunteer can check that this person is the attendee. Big button to mark as attended.

Considerations:
- We will need to add a new permission to vote and a different one for check-in. There are some users that should be able to vote but not check-in and viceversa. 
- Vote views now should require this new permission

References:
- Javascript QR code scanner: https://github.com/LazarSoft/jsqrcode

**Comment by casassg** [comment]
@alvarogirona this is not priority, but if you have time and you want to work on this. it would be sweet! :candy:

**Comment by ghost** [comment]
I will be working on it after this Monday in the check-in branch

**Comment by casassg** [comment]
@alvarogirona How is this going? Any progress?

**Comment by ghost** [comment]
There is a working table (with search and ordering) that shows the hacker that have not checked in and a link for each one to see the detail (name, surname, shirt size and diet).

I think I will modify the table to show all the hackers and the link text to be "check-in" or "uncheck" depending on if the hacker has been checked or not, and then on the detail show a button for check-in or for uncheck.

I'm having some trouble adding the QR reader.

**Comment by casassg** [comment]
It's only showing those who are not checked in. Admin's can mark someone as not attended in Admin console.

I added a view showing all non-attended hackers, and default the view to only confirmed hackers.

**Comment by casassg** [comment]
Added QR and it's working on my computer. Please check if it works on other computers :smile:
