### ISSUE TITLE
Add reminder admin action

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#22]
As an admin we want to send a reminder if an application hasn't responded

- [ ] Add invite date to model
- [ ] Show days since in admin list -> maybe new admin interface for this?
- [ ] Add reminder template

References:
- http://stackoverflow.com/questions/2223375/multiple-modeladmins-views-for-same-model-in-django-admin

**Comment by AsLogd** [comment]
Partially solved in 3093206be9e7779e80ea0da193a3520c9eb2209e

Where/how can I define a new e-mail template? (I suspect this is done in sendgrid)

**Comment by casassg** [comment]
I can set up an access account for you

**Comment by casassg** [comment]
Merged #49
