### ISSUE TITLE
Add automatic deployment

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#23]
References:
- https://kjaer.io/travis/

**Comment by rgascons** [comment]
Do we have tests? Without them having TravisCI is kinda useless

**Comment by casassg** [comment]
No tests (no time). But they can be easily added. But this is more to use Travis as auto-deployment tool.

**Comment by casassg** [comment]
Right now deployment is easy as it's only git pull, run refresh script and restart service

**Comment by casassg** [comment]
Not doing it
