### ISSUE TITLE
QR codes are not displaying

### ISSUE THREAD

**Issue by qaisjp** [HackAssistant/registration#240]
QR codes do not display because Google's QR Code API is deprecated

https://developers.google.com/chart/infographics/docs/qr_codes

(The API is currently down, and there's no guarantee for it to come back up because it is deprecated.)

**Comment by casassg** [comment]
Should we move away from QR codes in general? The UI has also some issues as Video Web API is still not great. At HackCU we ended up using just the search. 

An option would be to make the search with autocomplete so that it redirects to the check-in hacker page directly.

**Comment by casassg** [comment]
Alternative for QR scanners:

- https://github.com/nimiq/qr-scanner
- https://github.com/schmich/instascan#example-setup


We would need to benchmark this

**Comment by casassg** [comment]
An alternative to generate QR codes: http://goqr.me/api/
