### ISSUE TITLE
Admin Tab leads to 500 Server Error

### ISSUE THREAD

**Issue by s-fletcher** [HackAssistant/registration#281]
## Is this a BUG REPORT or FEATURE REQUEST?
Bug report

## What happened
Clicking on admin tab leads to a 500 server error
I've attached a screenshot at the bottom of what I get when I run it locally.

## What you expected to happen
Open the admin tab

## How to reproduce it (as minimally and precisely as possible)
Log into an admin account and go to the admin tab

## Anything else we need to know?
Running on heroku using SendGrid

## Environment
- Browser version: Version 77.0.3865.90 (Official Build) (64-bit)
- Domain: http://hacklahoma.herokuapp.com/

(Optional)
- Python version (`python --version`)
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

Screenshot:
![screencapture-localhost-8000-admin-2019-10-06-19_23_34](https://user-images.githubusercontent.com/11020347/66278506-51a08900-e86f-11e9-8e6f-5cfa48ab1d1b.png)

**Comment by casassg** [comment]
Updated django-jet dependency. Should be fine now
