### ISSUE TITLE
Set Max votes for application

### ISSUE THREAD

**Issue by Casassarnau** [HackAssistant/registration#287]
## Is this a BUG REPORT or FEATURE REQUEST?
Feature request

## What happened

In the begining of applications when an organizer is voting, s/he will vote everyone in the begining.
In order to balance votes per aplication it would be nice to set a max number of votes.
## What you expected to happen
When an application have X votes, the application will not be showed for review to any more organizers.
## How to reproduce it (as minimally and precisely as possible)
In the select from the data base, set a max amount of the count attribute with a where.

**Comment by casassg** [comment]
@Casassarnau pls remember to assign this to whoever is working on it. I can also add them to the org
