### ISSUE TITLE
Add Mentors, Sponsors and Volunteers

### ISSUE THREAD

**Issue by Casassarnau** [HackAssistant/registration#288]
## Is this a BUG REPORT or FEATURE REQUEST?
Feature request

## What happened

In order to check in/meals/baggage the sponsors, mentors, volunteers in the hack. We need this users in the data base.

## What you expected to happen
Mentors, volunteers and sponsors will be able to apply and then we could check them in, check meals, etc. So we would get even more data important for our logistics team displayed in the web.

## How to reproduce it (as minimally and precisely as possible)

- [x] Make user types.

- [x] Make new registrations by type.

- [x] Make sponsor applications.

- [x] Make volunteer applications.

- [x] Make mentor applications.

- [x] Make volunteer list.

- [x] Make sponsor list.

- [x] Make mentor list.

(I didn't add the stats because there's a current issue on this)

**Comment by casassg** [comment]
Curious, do you plane to migrate here the meal check-in here? also, can you elaborate on the design for this? Also, plans to update the hardware plugin?

**Comment by Casassarnau** [comment]
I didn't know the meals check-in is not at Hackassistant. We will try our best in order to get those features to Hackassistant as soon as possible. 
The idea is that the hackers, mentors, volunteers and sponsors could apply in Hackassistant. In order to do that we will have to add new forms, new attributes to the model user and application. And then the organizers depending in which type of organizer is, could accept mentors/volunteers. So we will have to add views of applications like the dubbious one but for mentors, volunteers and sponsors. Also fix the stats in order to show the hackers stats. And make that vounteers only can check-in if they application status is attended.
We currently don't have plans to update the hardware plugin this year.

**Comment by casassg** [comment]
Please, can you share a draft of what the updates would be? (model updates, views updates and view structure) Or at least how you thinking of them (write what you would need if you were to take on this in the future)
