### ISSUE TITLE
Create user from admin page BUG

### ISSUE THREAD

**Issue by Casassarnau** [HackAssistant/registration#313]
## Is this a BUG REPORT or FEATURE REQUEST?
bug report

## What happened
(Include screenshots when possible)
Happy error 500 when trying to create a user from admin.

## What you expected to happen
Create a user

## How to reproduce it (as minimally and precisely as possible)
just click on create new user on admin.

## Anything else we need to know?
Yep, this is beacuse the form is trying to create has no password1 and password2 fields. If you add them then it misses the password from the form. If you change the form as well as the fields with a correct form and fields, then the password doesn't get hashed. :)
What it have to be done is create a new form like the UserChangeForm but UserCreateForm with password and password2 like the register form. Then add clean password in order to check if the 2 passwords are the same. Then override the save method in order to don't commit the user and make user.set_password(cleaned_data['password']) in order to hash the password. and then save the user if commit is true. Little example is in the second answer of this post: https://stackoverflow.com/questions/15514912/django-admin-not-hashing-custom-user-password

## Environment
- Browser version (Ex: Google Chrome 62.0.3202.94 (64-bit)...):
- Domain: 
- Others:

(Optional)
- Python version (`python --version`)
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by casassg** [comment]
Another issue that you can take is to clean a bit the templates for PR/issues. Would you mind taking on that?
