### ISSUE TITLE
Decide domain and application external name

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#32]
I was thinking on labeling it as **My HackUPC** _wow such originality_

**Comment by ofpau** [comment]
/j Maybe even **La meva HackUPC**? 😏

**Comment by rgascons** [comment]
La_ meva HackUPC

**Comment by casassg** [comment]
La_HackUPC

**Comment by casassg** [comment]
my.hackupc.com ?

**Comment by ofpau** [comment]
Yes I'd go for this

**Comment by ani300** [comment]
I'd go with la.hackupc.com, but I'm not trustable with names

**Comment by dasilvacontin** [comment]
I'm down for la.hackupc.com tbh

**Comment by casassg** [comment]
Problem is this is public for hackers. Should be something which don't make us explain memes we have

**Comment by dasilvacontin** [comment]
Is it hard to make `my` redirect to `la`?

**Comment by rgascons** [comment]
Case closed

**Comment by casassg** [comment]
Not hard @dasilvacontin could be cnamed.. but I would do the other way. my.hackupc.com sounds more serious externally. At the same time that sounds exactly like PennApps -.-

**Comment by dasilvacontin** [comment]
Using 'my' feels dull and boring to me. I'd prefer something new. Doesn't have to be 'la'.

**Comment by casassg** [comment]
@dasilvacontin what about register.hackupc.com, app.hackupc.com, admin.hackupc.com... Using my would be good for people to remember easily.

**Comment by dasilvacontin** [comment]
@casassg What's the purpose of the page? What functionalities does it offer?

**Comment by casassg** [comment]
@dasilvacontin

- Application management and review (for admins - us)
- Email invites to hackers
- Confirm/Cancel link for hackers
- Ticket email to hackers
- Checkin (needs to be done)

**Comment by dasilvacontin** [comment]
I don't really get the following, could you elaborate? 

- Email invites to hackers
- Ticket email to hackers
- Checkin (needs to be done)

> Application management and review (for admins - us)

Does it need to go together in the same app as the others?

**Comment by casassg** [comment]
Stays as my.hackupc.com because it's easier for everyone to remember. Also bc we already have the SSL
