### ISSUE TITLE
Create test set to test the app locally

### ISSUE THREAD

**Issue by Reynau** [HackAssistant/registration#38]
It should be good to create a test set to try the app locally or a script to create test sets

**Comment by casassg** [comment]
It's called fixtures: https://docs.djangoproject.com/en/1.10/howto/initial-data/

Documentation on usage should be added to README.md as well

**Comment by AsLogd** [comment]
Added a fixture in 6d327db17620e6be05977890f8ab2e7f6a119703
I'm waiting to solve problems with sendgrid before PR

**Comment by casassg** [comment]
Merged #49
