### ISSUE TITLE
Add hacker to travel reimbursement list if travel reimbursement

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#39]
- Add new list "Travel reimbursement" in Sendgrid
- If hacker with travel reimbursement confirms add to list (as well as general list)

**Comment by casassg** [comment]
@ofpau if you can do it, that would make things easier.

**Comment by ofpau** [comment]
Will start working on it soon™

**Comment by casassg** [comment]
Let's close this and keep conversation in #51
