### ISSUE TITLE
Pre formatted descriptions

### ISSUE THREAD

**Issue by AsLogd** [HackAssistant/registration#48]
Desceiptions of applications often have a format which would be helpful if maintained (\n an such). I think that adding \<pre> in description would improve the readability of some applications

**Comment by casassg** [comment]
We would need to mark the field as safe. It's just django striping html from the text to avoid any injection

**Comment by casassg** [comment]
https://docs.djangoproject.com/en/1.10/ref/templates/builtins/ -> safe

**Comment by casassg** [comment]
Added on #130
