### ISSUE TITLE
Command to add hackers with reimbursement to mail list

### ISSUE THREAD

**Issue by ofpau** [HackAssistant/registration#51]
This substitutes https://github.com/hackupc/mercuryhack/issues/39.

Create a [command](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/) to add to a mail list all hackers that have been assigned some travel reimbursement.

The mail list on SendGrid can be the already existing _HackUPC W17 Travel Reimbursement_.

**Comment by casassg** [comment]
done in #63
