### ISSUE TITLE
Fix server error on cancel

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#58]
For some reason when cancelling the invite to HackUPC, SendGrid returns a 400 error when trying to delete the user from the HackUPC List. Check why is this happening.

**Comment by ofpau** [comment]
Working on it [here](https://github.com/hackupc/mercuryhack/tree/fix_cancel). The branch now contains an error handling to avoid an internal error. Next step is to fix the root of the problem.

**Comment by casassg** [comment]
:sheep: it
