### ISSUE TITLE
Get stats about t-shirt sizes & diets

### ISSUE THREAD

**Issue by gonsp** [HackAssistant/registration#69]

**Comment by ofpau** [comment]
@gonmolon Could I ask for more detail about this? We could do a command (like the one to fetch new form answers) that prints out some stats. Would that be okay? 
What stats do we want? I can think of "number of t-shirts of each size" and "number of people for each diet type". Anything else?
With these answers I can work on this tomorrow afternoon ☺

**Comment by ofpau** [comment]
Oh I see this is partially contained in #57. Is this a subset of that issue or it can be treated as a different one?

**Comment by gonsp** [comment]
Yep, it is a subset of that issue. I didn't see it, sorry. Btw, @quim-motger already got the data I needed but it still would be sweet to have this functionality for future occasions.
