### ISSUE TITLE
Make login temporary

### ISSUE THREAD

**Issue by rgascons** [HackAssistant/registration#79]

**Comment by casassg** [comment]
Could you please elaborate?

**Comment by casassg** [comment]
@rgascons pls?

**Comment by rgascons** [comment]
Apologies for the delay:

I found out that one doesn't log off after a period of time. Would be interesting to have a session  active for a period of time unless it's stated otherwise via a check box. 

Reason being I had this account opened in my laptop whose not mine for nearly two months and I didn't realize it.

**Comment by casassg** [comment]
Ugh okay. Time to dig into some Django session config

**Comment by rgascons** [comment]
This is low priority, just wanted to keep track of the issue :)

**Comment by rgascons** [comment]
`SESSION_COOKIE_AGE = 60 * 3600 * 24 * 7`
in settings.py to set logout time in seconds

**Comment by casassg** [comment]
See new interface. Session expiracy is undefined if click "Remember me" on sign in. I need to check what's the default value otherwise.

**Comment by rgascons** [comment]
Is this still up?

**Comment by casassg** [comment]
I need to check how does this stay on new version

**Comment by casassg** [comment]
Also, I need to stop commenting and closing

**Comment by casassg** [comment]
Closing this as I have not seen more reports on this.
