### ISSUE TITLE
Application confirmation view

### ISSUE THREAD

**Issue by casassg** [HackAssistant/registration#8]
Design confirmation view

Should include:
- Button to cancel application
- Clear message of thanks for confirming

Should do:
- Send email of confirmation to applicant
- Check states are correct before confirming
- Should extend base design and have consistency with cancel view

**Comment by casassg** [comment]
Started  here  68587680d

**Comment by casassg** [comment]
Ignore this commit. I messed up the number. I meant #7

**Comment by ofpau** [comment]
Continued here https://github.com/hackupc/mercuryhack/commit/2c5b2e2e780395be8bbaf140776844f9d75b8796 and here https://github.com/hackupc/mercuryhack/commit/15b2bf64c139d786116f4fb144ce0da9eaca69d9

Left to do:
- Send email of confirmation to applicant

**Comment by casassg** [comment]
closed at #14
