### ISSUE TITLE
Migrate DB from SQLite to a more scalable alternative on Production

### ISSUE THREAD

**Issue by rgascons** [HackAssistant/registration#87]
Among others, options are:

- Postgres
- MySQL

I'm leaning towards Postgres, as we're all more familiar with it.

**Comment by rgascons** [comment]
If the database is small (haven't checked it), with this steps :

- Backup current SQLite Database
- Pump database data into a JSON file `python manage.py dumpdata > database.json`
- Modify the database configuration in settings.py, then run `python manage.py syncdb` and `python manage.py migrate`  to configure the new database with the models and default settings
- Run `python manage.py sqlflush` to empy the database and make it ready for the JSON import
- Import the data with `manage.py loaddata dump.json`

This process loads the whole JSON into memory, we might first want to check out the size of the file before proceeding.

**Comment by ani300** [comment]
+1 to Postgres

**Comment by casassg** [comment]
Agree with @ani300  postgres should be the one in production. Also we dont need to do any data migration as we will start with data from scratch. I'll export the json and save it as a backup in our Google Drive for last edition.

**Comment by casassg** [comment]
Beta version is running on Postgres already 👍
